// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// src/app/layout.tsx
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { Providers } from './providers';
import { LayerToggle } from '@/components/layout/layer-toggle';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Kalachakra',
  description: 'Interactive exploration of Vedic cosmology with lokas, yugas, and manvantaras',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <div className="min-h-screen bg-gradient-to-br from-slate-50 to-amber-50">
            {/* Header Navigation */}
            <nav className="bg-white/80 backdrop-blur-sm border-b border-amber-200">
              <div className="container mx-auto px-4 py-3 flex items-center justify-between">
                <div>
                  <h1 className="text-xl font-bold text-amber-900">
                  Kalachakra - The Vedic Cosmology Atlas
                  </h1>
                  <p className="text-sm text-amber-700">
                    Interactive exploration of cosmic realms and time cycles
                  </p>
                </div>
                <LayerToggle />
              </div>
            </nav>
            
            {/* Main Content */}
            <main className="container mx-auto px-4 py-6">
              {children}
            </main>
          </div>
        </Providers>
      </body>
    </html>
  );
}
